namespace OrangeIntel.Domain.Entities;

public class Report
{
    public Guid Id { get; set; } = Guid.NewGuid();
    
    // Spec: report_type, title, content (jsonb), format, generated_by, generated_at
    public string ReportType { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    
    // Postgres JSONB
    public string ContentJson { get; set; } = "{}";
    
    public string Classification { get; set; } = "TLP:AMBER";

    public string Format { get; set; } = "PDF";
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    
    public string GeneratedById { get; set; } = string.Empty;
    
    // Optional link to assessment if we want to keep it, but spec didn't enforce it.
    // I'll keep it nullable for backward compat if needed, or remove if strict.
    // Spec says "Generated by UUID REFERENCES users(id)".
    // GeneratedById handles the user reference.
}
